### ISSUE TITLE
install Fail

### ISSUE THREAD

**Issue by GitGnom** [fezrestia/pokego-map-overlay#7] opened 2017-02-21 08:47 UTC
Auf Android 6.0.1 kann ich es nicht installieren bei Samsung S7EDGE.
Schuldige, kann kein Englisch nur German

**Comment by fezrestia** [comment] 2017-02-22 03:18
Thank for your support, there is no problem, we have google translation : )
If you can let me know the error message of installation fail, it is great help.

**Comment by GitGnom** [comment] 2017-02-22 12:11
"Parsing error" or "A problem has occurred while parsing the package"

Have already tried to eliminate the error.

Google translator

**Comment by fezrestia** [comment] 2017-03-03 08:08
The cause of install fail may be Android signature V1/V2.

Previous APK only support signature V2.
New APK support both of signature V1/V2, this can be installed old Andoid version.

047ca15a0cf9e6c6aa9c2e59506b3426316276ec

**Comment by GitGnom** [comment] 2017-03-10 07:38
Good Morning,
Could install it without problems. Only, my place of residence (Germany) is not displayed on the map and it is all in Japanese / Chinese.
So the setting possibilities are to be guessed. Is there perhaps a way to change this?!?

Otherwise, I find it from the first view as an overlay very interesting.

**Comment by fezrestia** [comment] 2017-03-24 07:39
Hi, thank you for our confirmation.

The default map URL is p-go search app, and it is for Japanese local use.
You can customize URL loaded on the overlay view from "Base load URL" setting.
If Germany or EU map service URL is available, you can use it.

Anyway, the issue is fixed, and I close this.

Thanks.

**Closed as completed by fezrestia** 2017-03-24 07:39 UTC
